import { useContext } from "react";
import { AppContext } from "../context/AppContext";
import { useNavigate } from "react-router-dom";

import { delay, motion } from "motion/react";

import { assets, sampleImgs } from "../assets/assets";

const Header = () => {
  const { user, setShowLogin } = useContext(AppContext);
  const navigate = useNavigate();

  const handleClick = () => {
    if (user) {
      navigate("/result");
    } else {
      setShowLogin(true);
    }
  };

  return (
    <motion.div
      className="flex flex-col justify-center items-center text-center my-12 lg:my-18 xl:my-20"
      initial={{ opacity: 0.2, y: 100 }}
      transition={{ duration: 1 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
    >
      <motion.div
        className="text-stone-500 inline-flex text-center gap-2 bg-white px-6 py-1 rounded-full border border-blue-100"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2, duration: 0.8 }}
      >
        <p>The most modern text to image generator</p>
        <img src={assets.star_icon} alt="star" />
      </motion.div>
      <motion.h1
        className="text-4xl max-w-[450px] sm:text-7xl sm:max-w-[650px] mx-auto text-center mt-10"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4, duration: 2 }}
      >
        Turn <span className="text-blue-600">thoughts</span> into{" "}
        <span className="text-blue-500">images</span>, in seconds.
      </motion.h1>
      <motion.p
        className="text-center max-w-2xl mx-auto mt-5"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6, duration: 0.8 }}
      >
        Unleash your creativity using AI. Turn your imagination into visual art
        in seconds - type out your thoughts and watch the magic happen.
      </motion.p>
      <motion.button
        className="sm:text-lg text-white bg-black w-auto mt-8 px-12 py-2.5 flex items-center gap-2 rounded-full hover:scale-110 transition-all duration-300"
        onClick={handleClick}
        whileHover={{ scale: 1.2 }}
        whileTap={{ scale: 0.5 }}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{
          default: { duration: 0.5 },
          opacity: { delay: 0.8, duration: 1 },
        }}
      >
        Generate Images{" "}
        <img src={assets.star_group} alt="group of stars" className="h-7" />
      </motion.button>
      <motion.div
        className="grid grid-cols-2 md:grid-cols-2 lg:flex lg:flex-wrap justify-center mt-16 gap-8 px-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1, duration: 1 }}
      >
        {sampleImgs.map((item, index) => (
          <motion.img
            whileHover={{ scale: 1.05, duration: 0.2 }}
            className="rounded hover:scale-105 transition-all duration-300 cursor-pointer w-full md:w-auto lg:w-28"
            src={item}
            key={index}
          />
        ))}
      </motion.div>
      <p className="m-2 text-neutral-600">Images generated by WordCanvas</p>
    </motion.div>
  );
};

export default Header;
